export const ThePeopleAbi = [
  {
    inputs: [
      { internalType: "address", name: "defaultAdmin", type: "address" },
      { internalType: "address", name: "_countryCodes", type: "address" },
      { internalType: "address", name: "_citizenship", type: "address" },
      { internalType: "address", name: "_stateDepartment", type: "address" },
      { internalType: "address", name: "_voterRegistration", type: "address" },
      {
        internalType: "address",
        name: "_commemorativeEdition",
        type: "address",
      },
      { internalType: "address", name: "_awards", type: "address" },
      { internalType: "address", name: "_timelock", type: "address" },
      { internalType: "address", name: "_governor", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ContractNotPermissionless", type: "error" },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "CountryIsNotCurrentlyInList",
    type: "error",
  },
  { inputs: [], name: "ERC1167FailedCreateClone", type: "error" },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "NationAlreadyExists",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "citizenship",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "stateDepartment",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "voterRegistration",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "commemorativeEdition",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "awards",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "timelock",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "governor",
        type: "address",
      },
    ],
    name: "ImplementationUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "isPermissionless",
        type: "bool",
      },
    ],
    name: "IsCreationPermissionless",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "timelock",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "governor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "countryCode",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "voterRegistration",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "citizenship",
        type: "address",
      },
    ],
    name: "JuristictionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "citizenship",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "nation",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "founder",
        type: "address",
      },
    ],
    name: "NationCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "citizenship",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "StateDepartment",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "federalVoterRegistration",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "awards",
        type: "address",
      },
    ],
    name: "NationDetails",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "countryCodes",
    outputs: [
      { internalType: "contract CountryCodes", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_symbol", type: "string" },
      { internalType: "address", name: "founder", type: "address" },
      { internalType: "address", name: "initialVerifier", type: "address" },
      { internalType: "string", name: "defaultCitizenshipURI", type: "string" },
    ],
    name: "createNation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "contract CitizenshipWithRegistry",
        name: "citizenship",
        type: "address",
      },
      {
        internalType: "contract StateDepartment",
        name: "stateDepartment",
        type: "address",
      },
      {
        internalType: "contract VoterRegistration",
        name: "voterRegistration",
        type: "address",
      },
      {
        internalType: "contract CommemorativeEdition",
        name: "commemorativeEdition",
        type: "address",
      },
      { internalType: "contract Awards", name: "awards", type: "address" },
      {
        internalType: "contract JuristictionTimelock",
        name: "timelock",
        type: "address",
      },
      { internalType: "contract Governor", name: "governor", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isPermissionless",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "nations",
    outputs: [
      { internalType: "string", name: "nation", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "address", name: "citizenship", type: "address" },
      { internalType: "address", name: "stateDepartment", type: "address" },
      {
        internalType: "address",
        name: "federalVoterRegistration",
        type: "address",
      },
      { internalType: "address", name: "founder", type: "address" },
      { internalType: "address", name: "awards", type: "address" },
      { internalType: "address", name: "federalTimelock", type: "address" },
      { internalType: "address", name: "federalGovernor", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "togglePermissionless",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_citizenship", type: "address" },
      { internalType: "address", name: "_stateDepartment", type: "address" },
      { internalType: "address", name: "_voterRegistration", type: "address" },
      {
        internalType: "address",
        name: "_commemorativeEdition",
        type: "address",
      },
      { internalType: "address", name: "_awards", type: "address" },
      { internalType: "address", name: "_timelock", type: "address" },
      { internalType: "address", name: "_governor", type: "address" },
    ],
    name: "updateImplementation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
