import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  useWatchContractEvent,
  useBlockNumber,
  useClient,
  useAccount,
} from "wagmi";
import { ThePeopleAbi } from "../utils/abis/ThePeopleAbi";
import { usePublicClient, useConfig, useReadContract } from "wagmi";
import { useEffect } from "react";
import { ThePeopleAddress } from "../utils/constants/deployments";
import { decodeEventLog } from "viem";
import { VerifierAddress } from "../utils/constants/deployments";
import Layout from "../components/layout/layout";
import ActionBar from "../components/action/actionBar";
import HomeTable from "../components/homeTable";

import useGetCountryByAddress from "../utils/hooks/useGetCountryByAddress";
import useGetNationDetails from "../utils/hooks/useGetNationDetails";
import SupportedCountriesDropdown from "../components/inline/supportedCountriesDropdown";

import StepOne from "../components/timeline/stepOne";

const Home: NextPage = () => {
  const config = useConfig();
  const publicClient = usePublicClient();
  const account = useAccount();

  const nation = useGetNationDetails("USA");

  const address = "0x70ebad30a31657a9cf7a748269c2fb0e63c2e4b7";
  // const address = "0xA70632CA8173FE5db9fa8E5e7b9E691778fe4D45"

  const country = useGetCountryByAddress(address);

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <ul className="timeline timeline-snap-icon max-md:timeline-compact timeline-vertical">
          <StepOne />
          <li>
            <hr />
            <div className="timeline-middle">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="h-5 w-5"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <div className="timeline-end mb-10">
              <time className="font-mono italic">Step 1</time>
              <div className="text-lg font-black">
                Claim your Citizenship on Nation State
              </div>
              Once you're verified on Coinbase, you can claim your citizenship
              on Nation state. Select your country from the dropdown{" "}
              <SupportedCountriesDropdown
                countries={[{ name: "United States", code: "US", emoji: "🇺🇸" }]}
              />
              and click "claim citizenship". Currently we only support the USA,
              but the world is coming soon!
              <br />
              <button className="btn btn-primary btn-sm ml-2 mt-10">
                Claim your Citizenship
              </button>
            </div>
            <hr />
          </li>
          <li>
            <hr />
            <div className="timeline-middle">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="h-5 w-5"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <div className="timeline-start md:text-end mb-10">
              <time className="font-mono italic">Step 3</time>
              <div className="text-lg font-black">Register to Vote</div>
              Once you have a citizenship token, you need to lock it in a
              "juristiction" to begin voting. To start with there is only the
              Federal juristicion, a place to vote for the whole nation. In the
              future it will be possilbe to launch States and Local governments.
            </div>
            <hr />
          </li>
          <li>
            <hr />
            <div className="timeline-middle">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="h-5 w-5"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <div className="timeline-end mb-10">
              <time className="font-mono italic">2007</time>
              <div className="text-lg font-black">iPhone</div>
              iPhone is a line of smartphones produced by Apple Inc. that use
              Apple's own iOS mobile operating system. The first-generation
              iPhone was announced by then-Apple CEO Steve Jobs on January 9,
              2007. Since then, Apple has annually released new iPhone models
              and iOS updates. As of November 1, 2018, more than 2.2 billion
              iPhones had been sold. As of 2022, the iPhone accounts for 15.6%
              of global smartphone market share
            </div>
            <hr />
          </li>
          <li>
            <hr />
            <div className="timeline-middle">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="h-5 w-5"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <div className="timeline-start md:text-end mb-10">
              <time className="font-mono italic">2015</time>
              <div className="text-lg font-black">Apple Watch</div>
              The Apple Watch is a line of smartwatches produced by Apple Inc.
              It incorporates fitness tracking, health-oriented capabilities,
              and wireless telecommunication, and integrates with iOS and other
              Apple products and services
            </div>
          </li>
        </ul>
      </div>
    </Layout>
  );
};

export default Home;
