import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useWatchContractEvent, useBlockNumber, useClient } from "wagmi";
import { ThePeopleAbi } from "../utils/abis/ThePeopleAbi";
import { usePublicClient, useConfig, useReadContract } from "wagmi";
import { useEffect } from "react";
import { ThePeopleAddress } from "../utils/constants/deployments";
import { decodeEventLog } from "viem";
import { VerifierAddress } from "../utils/constants/deployments";
import Layout from "../components/layout/layout";
import ActionBar from "../components/action/actionBar";
import HomeTable from "../components/homeTable";
import { VerifierABI } from "../utils/abis/VerifierAbi";

import useGetCountryByAddress  from "../utils/hooks/useGetCountryByAddress";

const Home: NextPage = () => {
  const config = useConfig();
  const publicClient = usePublicClient();

  // useEffect(() => {
  //   const getEvents = async () => {
  //     const events = await publicClient
  //       ?.getLogs({
  //         address: ThePeopleAddress,
  //         abi: ThePeopleAbi,
  //         topics: [],
  //         fromBlock: BigInt(10677037),
  //         toBlock: BigInt(10679037),
  //       })
  //       .then((logs) => {
  //         logs.forEach((log) => {
  //           const topics = decodeEventLog({
  //             abi: ThePeopleAbi,
  //             ...log,
  //           });
  //           console.log(topics);
  //         });
  //       });
  //   };

  //   getEvents();
  // }, []);

  const address = "0x70ebad30a31657a9cf7a748269c2fb0e63c2e4b7";
  // const address = "0xA70632CA8173FE5db9fa8E5e7b9E691778fe4D45"

  const country = useGetCountryByAddress(address);
  console.log("this country 🚀 ~ country:", country)
  
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <div className="hero min-h-screen">
          <div className="hero-content text-center flex flex-col items-center">
            <div className="max-w-lg">
              <ActionBar />
            </div>
            <div className="max-w-lg">
              <HomeTable />
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
